application:
  title: KR Simple application
  description: Application description for this one
  logback:
    access:
      config:
        path: logback-access.xml
swagger:
  enabled: true

---
server:
  port: 8080
spring:
  profiles: local

---
server:
  port: 8080
spring:
  profiles: dev

---
server:
  port: 8080
spring:
  profiles: prod
swagger:
  enabled: false
